on:
  workflow_dispatch:
  push:
    tags: ["v*", "test*"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - package: ioshelfka-mono-nerd
            artifact: IoshelfkaMonoNerd.zip
          - package: ioshelfka-term-nerd
            artifact: IoshelfkaTermNerd.zip
          - package: ioshelfka-mono
            artifact: IoshelfkaMono.zip
          - package: ioshelfka-term
            artifact: IoshelfkaTerm.zip
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          extra-conf: |
            extra-experimental-features = nix-command flakes

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          #!/usr/bin/env bash
          set -eux

          # Build only the Mono Nerd variant for now. Rest can be handled with
          # a matrix in the future.
          nix build .#${{ matrix.package }} --print-build-logs || exit 1

          # Contains built fonts and a NerdFonts directory for *patched* fonts.
          # Upload both of them, Nix might be able to resolve fonts from the
          # unpacked archive.
          zip -vr9  ${{ matrix.artifact }} ./result/share/fonts/truetype

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact }}
          asset_name: IoshelfkaMonoNerd.zip
          tag: ${{ github.ref }}
          overwrite: true
